"""Typed, fail-closed verifier for boxed mathematical answers."""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Typed boxed-math verifier generated by nemotron_gym."""
from __future__ import annotations

import json
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")

_INTERVAL_TYPES = {"interval", "set"}
_OPENERS = {"(": ")", "[": "]", "{": "}"}


class UnsupportedAnswer(ValueError):
    """The answer cannot be compared soundly by its declared comparator."""


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _extract_boxed(text: str) -> str | None:
    idx = text.rfind(r"\boxed{")
    if idx < 0:
        return None
    depth = 0
    start = idx + len(r"\boxed{")
    for i in range(start, len(text)):
        char = text[i]
        if char == "{":
            depth += 1
        elif char == "}":
            if depth == 0:
                return text[start:i].strip()
            depth -= 1
    return None


def _strip_math_delimiters(text: str) -> str:
    value = text.strip()
    pairs = ((r"\[", r"\]"), ("$$", "$$"), (r"\(", r"\)"))
    changed = True
    while changed:
        changed = False
        for left, right in pairs:
            if value.startswith(left) and value.endswith(right):
                value = value[len(left) : -len(right)].strip()
                changed = True
                break
        if value.startswith("$") and value.endswith("$") and value.count("$") == 2:
            value = value[1:-1].strip()
            changed = True
    return value


def _normalize(text: str) -> str:
    value = _strip_math_delimiters(text)
    replacements = {
        "−": "-",
        "–": "-",
        "∞": "oo",
        r"\infty": "oo",
        r"\left": "",
        r"\right": "",
        r"\!": "",
        r"\,": "",
        r"\;": "",
        r"\:": "",
    }
    for old, new in replacements.items():
        value = value.replace(old, new)
    return re.sub(r"\s+", " ", value).strip()


def _normalize_text(text: str) -> str:
    value = _normalize(text.strip().rstrip(".")).strip().rstrip(".")
    return re.sub(r"\s+", " ", value).casefold()


def _split_top_level(text: str, separators: set[str]) -> list[str]:
    parts: list[str] = []
    stack: list[str] = []
    start = 0
    for index, char in enumerate(text):
        if char in _OPENERS:
            stack.append(_OPENERS[char])
        elif stack and char == stack[-1]:
            stack.pop()
        elif char in separators and not stack:
            parts.append(text[start:index].strip())
            start = index + 1
    parts.append(text[start:].strip())
    return parts


def _scalar(text: str):
    from sympy import Basic, Symbol, sympify
    from sympy.parsing.latex import parse_latex

    value = _normalize(text)
    if not value:
        raise UnsupportedAnswer("empty scalar")
    if re.fullmatch(r"[+\-]?(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?%?", value):
        value = value.replace(",", "")
    if value.endswith("%"):
        value = f"({value[:-1]})/100"
    if re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", value):
        return Symbol(value)
    latex_like = bool(
        "\\" in value
        or "{" in value
        or "'" in value
        or re.search(r"(?:\d|\))(?=[A-Za-z])", value)
    )
    if not latex_like:
        value = value.replace("^", "**")
    try:
        parsed = parse_latex(value) if latex_like else sympify(value)
    except Exception as error:
        raise UnsupportedAnswer(f"scalar parse error: {error}") from error
    if not isinstance(parsed, Basic) or parsed.is_Relational or parsed.is_Boolean:
        raise UnsupportedAnswer(f"not a scalar expression: {type(parsed).__name__}")
    return parsed


def _scalar_equal(actual: str, expected: str) -> bool:
    from sympy import simplify

    left = _scalar(actual)
    right = _scalar(expected)
    return bool(left == right or simplify(left - right) == 0)


def _endpoint(text: str):
    from sympy import oo

    value = _normalize(text).replace("+oo", "oo")
    if value == "oo":
        return oo
    if value == "-oo":
        return -oo
    return _scalar(value)


def _interval(text: str):
    from sympy import Interval

    value = _normalize(text)
    if len(value) < 5 or value[0] not in "([" or value[-1] not in ")]":
        raise UnsupportedAnswer(f"invalid interval syntax: {text!r}")
    endpoints = _split_top_level(value[1:-1], {","})
    if len(endpoints) != 2:
        raise UnsupportedAnswer(f"interval needs two endpoints: {text!r}")
    return Interval(
        _endpoint(endpoints[0]),
        _endpoint(endpoints[1]),
        left_open=value[0] == "(",
        right_open=value[-1] == ")",
    )


def _set_expression(text: str):
    from sympy import FiniteSet, Tuple, Union

    value = _normalize(text)
    union_parts = re.split(r"\s*(?:\\cup|∪)\s*", value)
    if len(union_parts) > 1:
        if any(not part for part in union_parts):
            raise UnsupportedAnswer("empty union member")
        return Union(*(_set_expression(part) for part in union_parts))
    if value.startswith("{") and value.endswith("}"):
        members = _split_top_level(value[1:-1], {","})
        if members == [""]:
            return FiniteSet()
        parsed_members = []
        for member in members:
            if member.startswith("(") and member.endswith(")"):
                values = _split_top_level(member[1:-1], {","})
                parsed_members.append(Tuple(*(_scalar(item) for item in values)))
            else:
                parsed_members.append(_scalar(member))
        return FiniteSet(*parsed_members)
    return _interval(value)


def _set_equal(actual: str, expected: str) -> bool:
    from sympy import EmptySet

    def finite_members(text: str):
        value = _normalize(text)
        if not (value.startswith("{") and value.endswith("}")):
            raise UnsupportedAnswer(f"invalid finite-set syntax: {text!r}")
        members = _split_top_level(value[1:-1], {","})
        if members == [""]:
            return frozenset()
        canonical = []
        for member in members:
            if member.startswith("(") and member.endswith(")"):
                values = _split_top_level(member[1:-1], {","})
                canonical.append(("tuple", tuple(_scalar(item) for item in values)))
                continue
            try:
                canonical.append(("scalar", _scalar(member)))
            except UnsupportedAnswer:
                normalized = _normalize_text(member)
                if not normalized:
                    raise UnsupportedAnswer("empty finite-set member")
                canonical.append(("text", normalized))
        return frozenset(canonical)

    actual_value = _normalize(actual)
    expected_value = _normalize(expected)
    if (
        actual_value.startswith("{")
        and actual_value.endswith("}")
        and expected_value.startswith("{")
        and expected_value.endswith("}")
        and not re.search(r"\\cup|∪", actual_value + expected_value)
    ):
        return finite_members(actual) == finite_members(expected)

    left = _set_expression(actual)
    right = _set_expression(expected)
    return bool(left == right or left.symmetric_difference(right) == EmptySet)


def _sequence(text: str, answer_type: str) -> list[str]:
    value = _normalize(text)
    delimiters = {"tuple": ("(", ")"), "list": ("[", "]")}
    left, right = delimiters[answer_type]
    if not value.startswith(left) or not value.endswith(right):
        raise UnsupportedAnswer(f"invalid {answer_type} syntax: {text!r}")
    members = _split_top_level(value[1:-1], {","})
    return [] if members == [""] else members


def _sequence_equal(actual: str, expected: str, answer_type: str) -> bool:
    left = _sequence(actual, answer_type)
    right = _sequence(expected, answer_type)
    return len(left) == len(right) and all(
        _scalar_equal(actual_member, expected_member)
        for actual_member, expected_member in zip(left, right, strict=True)
    )


def _equation(text: str):
    value = _normalize(text)
    parts = _split_top_level(value, {"="})
    if len(parts) != 2 or not all(parts):
        raise UnsupportedAnswer(f"invalid equation: {text!r}")
    return _scalar(parts[0]) - _scalar(parts[1])


def _equation_equal(actual: str, expected: str) -> bool:
    from sympy import simplify

    left = _equation(actual)
    right = _equation(expected)
    if simplify(left - right) == 0:
        return True
    if right == 0:
        return left == 0
    ratio = simplify(left / right)
    return bool(ratio != 0 and not ratio.free_symbols)


def _matches(actual: str, expected: str, answer_type: str) -> bool:
    if _normalize(actual) == _normalize(expected):
        return True
    if answer_type in _INTERVAL_TYPES:
        return _set_equal(actual, expected)
    if answer_type in {"tuple", "list"}:
        return _sequence_equal(actual, expected, answer_type)
    if answer_type == "equation":
        return _equation_equal(actual, expected)
    if answer_type == "scalar":
        return _scalar_equal(actual, expected)
    if answer_type == "text":
        return _normalize_text(actual) == _normalize_text(expected)
    raise UnsupportedAnswer(f"unsupported answer_type: {answer_type!r}")


def main() -> int:
    if not DATA.exists():
        print("status: missing-verifier-data", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    expected = data.get("expected_answer")
    answer_type = data.get("answer_type")
    if not isinstance(expected, str) or not isinstance(answer_type, str):
        print("status: invalid-verifier-data", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("status: missing-answer", file=sys.stderr)
        return 0
    raw = ANSWER.read_text(errors="replace")
    actual = _extract_boxed(raw)
    if actual is None:
        actual = raw.strip()
    print(f"answer_type={answer_type!r}")
    print(f"expected={expected!r}")
    print(f"actual={actual!r}")
    try:
        matched = _matches(actual, expected, answer_type)
    except UnsupportedAnswer as error:
        print(f"status: unsupported-or-parse-error: {error}")
        return 0
    print("verdict: match" if matched else "verdict: mismatch")
    return int(matched)


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as error:
        print(f"status: verifier-exception: {error}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
