"""Repack each output parquet with project-default snappy compression, generate
a README, and upload to `laion/nemotron-gym-<slug>` on the HuggingFace Hub.

Reads HF_TOKEN from environment (typically sourced from ~/secrets.env).
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
import tempfile
import time
from pathlib import Path


# slug-on-disk → HF repo name (kebab-case)
DATASETS: list[tuple[str, str, str]] = [
    # (parquet_filename, hf_repo, source_dataset_url)
    (
        "competitive_coding.parquet",
        "laion/nemotron-gym-competitive-coding",
        "nvidia/Nemotron-RL-coding-competitive_coding",
    ),
    (
        "math_openmathreasoning.parquet",
        "laion/nemotron-gym-math-openmathreasoning",
        "nvidia/Nemotron-RL-math-OpenMathReasoning",
    ),
    (
        "math_advanced_calculations.parquet",
        "laion/nemotron-gym-math-advanced-calculations",
        "nvidia/Nemotron-RL-math-advanced_calculations",
    ),
    (
        "math_stack_overflow.parquet",
        "laion/nemotron-gym-math-stack-overflow",
        "nvidia/Nemotron-RL-math-stack_overflow",
    ),
    (
        "knowledge_mcqa.parquet",
        "laion/nemotron-gym-knowledge-mcqa",
        "nvidia/Nemotron-RL-knowledge-mcqa",
    ),
    (
        "knowledge_web_search_mcqa.parquet",
        "laion/nemotron-gym-knowledge-web-search-mcqa",
        "nvidia/Nemotron-RL-knowledge-web_search-mcqa",
    ),
    (
        "knowledge_openqa.parquet",
        "laion/nemotron-gym-knowledge-openqa",
        "nvidia/Nemotron-RL-knowledge-openqa",
    ),
    (
        "knowledge_openqa_v2.parquet",
        "laion/nemotron-gym-knowledge-openqa-v2",
        "nvidia/Nemotron-RL-knowledge-openqa",
    ),
    (
        "instruction_following.parquet",
        "laion/nemotron-gym-instruction-following",
        "nvidia/Nemotron-RL-instruction_following",
    ),
    (
        "instruction_following_structured.parquet",
        "laion/nemotron-gym-instruction-following-structured",
        "nvidia/Nemotron-RL-instruction_following-structured_outputs",
    ),
    (
        "instruction_following_calendar.parquet",
        "laion/nemotron-gym-instruction-following-calendar",
        "nvidia/Nemotron-RL-Instruction-Following-Calendar-v2",
    ),
    (
        "reasoning_gym.parquet",
        "laion/nemotron-gym-reasoning-gym",
        "nvidia/Nemotron-RL-ReasoningGym-v1",
    ),
    (
        "agent_calendar.parquet",
        "laion/nemotron-gym-agent-calendar",
        "nvidia/Nemotron-RL-agent-calendar_scheduling",
    ),
    (
        "agent_workplace.parquet",
        "laion/nemotron-gym-agent-workplace",
        "nvidia/Nemotron-RL-agent-workplace_assistant",
    ),
    ("safety.parquet", "laion/nemotron-gym-safety", "nvidia/Nemotron-RL-Safety-v1"),
    (
        "safety_v2.parquet",
        "laion/nemotron-gym-safety-v2",
        "nvidia/Nemotron-RL-Safety-v1",
    ),
    (
        "identity_following.parquet",
        "laion/nemotron-gym-identity-following",
        "nvidia/Nemotron-RL-Identity-Following-v1",
    ),
    (
        "instruction_following_adversarial.parquet",
        "laion/nemotron-gym-instruction-following-adversarial",
        "nvidia/Nemotron-RL-Instruction-Following-Adversarial-v1",
    ),
]


README_TEMPLATE = """---
license: cc-by-4.0
task_categories:
  - reinforcement-learning
language:
  - en
tags:
  - harbor
  - nemotron-gym
  - rl
  - verifiable-rewards
size_categories:
  - {size_category}
---

# {repo_name}

Harbor-format conversion of [{source}](https://huggingface.co/datasets/{source}).

Each row contains:

| column | type | description |
| --- | --- | --- |
| `path` | string | Deterministic short ID (`<family>-<sha256[:12]>.tar.gz`) |
| `task_binary` | binary | Gzipped tar containing the full Harbor task |

The tarball contents follow Harbor's task layout:

```
instruction.md                # Prompt shown to the agent
environment/Dockerfile        # python:3.11-slim-bookworm base + task-specific pip deps
tests/test.sh                 # Verifier entrypoint (writes /logs/verifier/reward.txt)
tests/verifier.py             # Verifier implementation (embedded, deterministic)
tests/verifier_data.json      # Per-task verifier inputs (JSON, no code interpolation)
metadata.json                 # Provenance: source_dataset, row_index, family, ...
task.toml                     # Standard Harbor task config (cpu/memory/timeout defaults)
```

## Conversion details

Generated by the `data/nemotron_gym` adapter in
[OpenThoughts-Agent](https://github.com/open-thoughts/OpenThoughts-Agent).
Conversion is **secure-by-construction**:

- Dataset content is never interpolated into shell, Python, or Dockerfile source.
  All values flow through `tests/verifier_data.json` (JSON, parsed at runtime).
- Base image is name-pinned (`python:3.11-slim-bookworm`); pip specs validated
  against a strict allowlist regex.
- Text fields stripped of C0/C1 control characters; lengths capped; tarball
  paths validated against traversal / NUL / absolute-path attacks.
- Tarballs are deterministic (sorted entries, `mtime=0`, `uid/gid=0`) →
  reproducible bytes.

## Verifier family

`{verifier_family}` — see the source converter for full details.

## Usage with Harbor

```python
from datasets import load_dataset

ds = load_dataset("{repo_name}", split="train")
print(ds[0]["path"], len(ds[0]["task_binary"]))
```

To run a single task with Harbor:

```bash
# Extract one task to a directory and point Harbor at it
python - <<'PY'
import gzip, io, tarfile
from datasets import load_dataset
ds = load_dataset("{repo_name}", split="train")
row = ds[0]
with tarfile.open(fileobj=io.BytesIO(row["task_binary"]), mode="r:gz") as tar:
    tar.extractall("/tmp/{slug}-task")
PY
harbor run -t /tmp/{slug}-task -e daytona  # or -e docker
```

## Source

This dataset is a derivative of
[{source}](https://huggingface.co/datasets/{source}), part of NVIDIA's
[NeMo-Gym collection](https://huggingface.co/collections/nvidia/nemo-gym).
"""


VERIFIER_FAMILY_BY_REPO = {
    "competitive-coding": "stdio_diff (run /app/solution.py against hidden stdin/stdout test cases)",
    "math-openmathreasoning": "math_boxed (extract \\boxed{…}, sympy-compare to gold)",
    "math-advanced-calculations": "numeric_compare (numeric tolerance vs reference value)",
    "math-stack-overflow": "math_boxed (extract \\boxed{…}, sympy-compare to gold)",
    "knowledge-mcqa": "regex_letter (regex-extract chosen letter, case-insensitive)",
    "knowledge-web-search-mcqa": "regex_letter (regex-extract chosen letter, case-insensitive)",
    "knowledge-openqa": "normalized_text (normalize whitespace/case/punct, substring match)",
    "knowledge-openqa-v2": "llm_judge (LiteLLM, default `openai/gpt-4o-mini`, scored against reference answers as rubric — semantic-equivalence judging for paraphrasable long-form answers)",
    "instruction-following": "ifeval_constraints (IFEval-style constraint checker — paragraphs / words / forbidden / formatting)",
    "instruction-following-structured": "json_schema (parse agent JSON, validate against Draft 2020-12 schema)",
    "instruction-following-calendar": "calendar_constraints (parse agent JSON list; check exact event set, duration, window, declared constraints, and pairwise non-overlap)",
    "reasoning-gym": "reasoning_gym (delegate to upstream reasoning_gym scorer; normalized-match fallback)",
    "agent-calendar": "calendar_constraints (same complete contract as instruction-following-calendar)",
    "agent-workplace": "tool_call_match (JSON `{name, arguments}` compared to ground_truth tool calls; lossy single-step substitute for upstream stateful env)",
    "safety": "llm_judge (LiteLLM, default `openai/gpt-4o-mini`, scored against `principle` rubric)",
    "safety-v2": "safety_judge (LiteLLM, default `openai/gpt-4o-mini`, scored against `principle` rubric, with a heuristic refusal-detection fallback for sandboxes without `OPENAI_API_KEY` and a `/logs/agent` scan for the agent's response when `/app/response.txt` is missing — v2 fixes the 0% solve rate of v1)",
    "identity-following": "llm_judge (LiteLLM, default `openai/gpt-4o-mini`, scored against persona `principle`)",
    "instruction-following-adversarial": "llm_judge (LiteLLM, per-task `rubric` + `judge_prompt_template` from upstream row)",
}


def _size_category(num_bytes: int) -> str:
    if num_bytes < 1_000_000:
        return "n<1K"
    if num_bytes < 10_000_000:
        return "1K<n<10K"
    if num_bytes < 100_000_000:
        return "10K<n<100K"
    if num_bytes < 1_000_000_000:
        return "100K<n<1M"
    return "1M<n<10M"


def _repack_snappy(src: Path, dst: Path) -> tuple[int, int]:
    """Rewrite parquet with snappy compression. Returns (n_rows, dst_bytes)."""
    import pyarrow.parquet as pq

    table = pq.read_table(src)
    pq.write_table(table, dst, compression="snappy")
    return table.num_rows, dst.stat().st_size


def _build_readme(repo_name: str, source: str, slug: str, n_rows: int) -> str:
    return README_TEMPLATE.format(
        repo_name=repo_name,
        source=source,
        slug=slug,
        size_category=_size_category(n_rows * 1000),  # rough proxy
        verifier_family=VERIFIER_FAMILY_BY_REPO.get(slug, "see source"),
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--output-dir",
        default="data/nemotron_gym/output",
        type=Path,
        help="Directory containing the parquet files",
    )
    ap.add_argument(
        "--dataset",
        action="append",
        help="Specific parquet filename(s) to upload (default: all)",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="Repack + write README locally but skip HF upload",
    )
    ap.add_argument(
        "--private",
        action="store_true",
        help="Create repos as private",
    )
    args = ap.parse_args()

    token = os.environ.get("HF_TOKEN")
    if not token and not args.dry_run:
        print(
            "ERROR: HF_TOKEN not set. `source ~/secrets.env` or pass --dry-run",
            file=sys.stderr,
        )
        return 1

    if not args.dry_run:
        from huggingface_hub import HfApi, create_repo  # noqa: F401

        api = HfApi(token=token)
    else:
        api = None

    selected = set(args.dataset) if args.dataset else None
    summary: list[dict] = []
    for parquet_name, repo_name, source in DATASETS:
        if selected and parquet_name not in selected:
            continue
        src = args.output_dir / parquet_name
        if not src.exists():
            print(f"SKIP {parquet_name} — not found at {src}")
            continue
        slug = repo_name.split("/", 1)[1].removeprefix("nemotron-gym-")
        print(f"\n=== {repo_name}")
        print(f"  source: {src} ({src.stat().st_size:,} bytes)")
        t0 = time.time()
        with tempfile.TemporaryDirectory() as td:
            tmp = Path(td)
            staged_parquet = tmp / "tasks.parquet"
            n_rows, new_size = _repack_snappy(src, staged_parquet)
            print(
                f"  repacked: {new_size:,} bytes, {n_rows:,} rows ({time.time() - t0:.1f}s)"
            )
            readme = _build_readme(repo_name, source, slug, n_rows)
            (tmp / "README.md").write_text(readme)
            if args.dry_run:
                local_target = args.output_dir / f"{src.stem}.hf"
                local_target.mkdir(exist_ok=True)
                shutil.copy(staged_parquet, local_target / "tasks.parquet")
                (local_target / "README.md").write_text(readme)
                print(f"  [dry-run] wrote to {local_target}")
                summary.append({"repo": repo_name, "rows": n_rows, "uploaded": False})
                continue
            from huggingface_hub import create_repo

            create_repo(
                repo_id=repo_name,
                repo_type="dataset",
                private=bool(args.private),
                token=token,
                exist_ok=True,
            )
            t1 = time.time()
            api.upload_folder(
                folder_path=str(tmp),
                repo_id=repo_name,
                repo_type="dataset",
                commit_message=(
                    "Initial upload — Harbor-format conversion of "
                    f"{source} via OpenThoughts-Agent's data/nemotron_gym adapter"
                ),
            )
            print(
                f"  uploaded in {time.time() - t1:.1f}s -> https://huggingface.co/datasets/{repo_name}"
            )
            summary.append({"repo": repo_name, "rows": n_rows, "uploaded": True})

    print("\n=== Summary ===")
    for row in summary:
        status = "uploaded" if row["uploaded"] else "dry-run only"
        print(f"  {row['repo']:60s}  {row['rows']:>10,} rows  [{status}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
